volumes:
  pg_data:
  static:
  media:
  docs:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/app/media/
      - docs:/app/docs/
  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    build: ./nginx/
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 9080:80
    volumes:
      - static:/static
      - media:/app/media/
      - docs/:/usr/share/nginx/html/api/docs/
