# Generated by Django 4.2.16 on 2025-01-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shortlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
