# Generated by Django 4.2.16 on 2025-01-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_follow_subscriber_alter_gramuser_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique subscribe',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='check self-subscribe',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='subscriber',
            new_name='author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique subscribe'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('author')), _negated=True), name='check self-subscribe'),
        ),
    ]
