# Generated by Django 4.2.16 on 2025-02-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_follow_unique_subscribe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check self-subscribe',
        ),
    ]
